id: P000692
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:23.395188
source_metadata:
  id: bdr:W1PD90032
  title: བཙན་ལྷ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  volumes:
    52108bae0b984990a137918494482f1f:
      image_group_id: I1PD90108
      title: ''
      volume_number: 1
      total_pages: 694
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
