id: I774CB492
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:32:27+00:00'
last_modified: '2022-06-07T12:40:37.689608+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90032
  title: བཙན་ལྷ་རྫོང་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AE4B:
      image_group_id: I1PD90108
      title: ''
      total_pages: 694
      order: 1
      base_file: AE4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
